plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

require:
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  DisplayStyleGuide: true

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Max: 9

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

Style/GuardClause:
  Enabled: false
